# host and port of gremlin server, need to be consistent with host and port in rest-server.properties
host: 127.0.0.1
port: 8182

# timeout in ms of gremlin query
scriptEvaluationTimeout: 30000

channelizer: org.apache.tinkerpop.gremlin.server.channel.WsAndHttpChannelizer
graphs: {

}
scriptEngines: {
  gremlin-groovy: {
    plugins: {
      com.vortex.vortexdb.plugin.VortexGremlinPlugin: {},
      org.apache.tinkerpop.gremlin.server.jsr223.GremlinServerGremlinPlugin: {},
      org.apache.tinkerpop.gremlin.jsr223.ImportGremlinPlugin: {
        classImports: [
            java.lang.Math,
            com.vortex.vortexdb.backend.id.IdGenerator,
            com.vortex.vortexdb.type.define.Directions,
            com.vortex.vortexdb.type.define.NodeRole,
            com.vortex.vortexdb.traversal.algorithm.CustomizePathsTraverser,
            com.vortex.vortexdb.traversal.algorithm.CustomizedCrosspointsTraverser,
            com.vortex.vortexdb.traversal.algorithm.FusiformSimilarityTraverser,
            com.vortex.vortexdb.traversal.algorithm.VortexTraverser,
            com.vortex.vortexdb.traversal.algorithm.NeighborRankTraverser,
            com.vortex.vortexdb.traversal.algorithm.PathsTraverser,
            com.vortex.vortexdb.traversal.algorithm.PersonalRankTraverser,
            com.vortex.vortexdb.traversal.algorithm.ShortestPathTraverser,
            com.vortex.vortexdb.traversal.algorithm.SubGraphTraverser,
            com.vortex.vortexdb.traversal.optimize.Text,
            com.vortex.vortexdb.traversal.optimize.TraversalUtil,
            com.vortex.common.util.DateUtil
        ],
        methodImports: [java.lang.Math#*]
      },
#      org.apache.tinkerpop.gremlin.jsr223.ScriptFileGremlinPlugin: {
#        files: [scripts/empty-sample.groovy]
#      }
    }
  }
}
serializers:
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphBinaryMessageSerializerV1,
      config: {
        serializeResultToString: false,
        ioRegistries: [com.vortex.vortexdb.io.VortexIoRegistry]
      }
  }
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0,
      config: {
        serializeResultToString: false,
        ioRegistries: [com.vortex.vortexdb.io.VortexIoRegistry]
      }
  }
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV2d0,
      config: {
        serializeResultToString: false,
        ioRegistries: [com.vortex.vortexdb.io.VortexIoRegistry]
      }
  }
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV3d0,
      config: {
        serializeResultToString: false,
        ioRegistries: [com.vortex.vortexdb.io.VortexIoRegistry]
      }
  }
metrics: {
  consoleReporter: {enabled: false, interval: 180000},
  csvReporter: {enabled: false, interval: 180000, fileName: ./metrics/gremlin-server-metrics.csv},
  jmxReporter: {enabled: false},
  slf4jReporter: {enabled: false, interval: 180000},
  gangliaReporter: {enabled: false, interval: 180000, addressingMode: MULTICAST},
  graphiteReporter: {enabled: false, interval: 180000}
}
maxInitialLineLength: 4096
maxHeaderSize: 8192
maxChunkSize: 8192
maxContentLength: 65536
maxAccumulationBufferComponents: 1024
resultIterationBatchSize: 64
writeBufferLowWaterMark: 32768
writeBufferHighWaterMark: 65536
ssl: {
  enabled: false
}